server:
  port: 1111
spring:
  config:
    user-url: http://localhost:1188/User/
    hotel-url: http://localhost:1188/hotels/
    payment-url: http://localhost:1188/payment/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 1111
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: rykhvaihor@gmail.com
    password: npthhzbxjidtrbgw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: "http://localhost:9090/realms/book-hotel"
            jwk-set-uri: "http://localhost:9090/realms/book-hotel/protocol/openid-connect/certs"
keycloak:
  auth-server-url: http://localhost:9090
  realm: book-hotel
  resource: spring-boot-client
  credentials:
    secret: pJrSiE47lYdcQaA2qqrO7T2zg42ERcmJ
  use-resource-role-mappings: true
