server:
  port: 1188
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #Booking
        - id: booking-service
          uri: lb:http://BOOKING-SERVICE
          predicates:
            - Path=/books/**
           #Hotel
        - id: hotel-microservice
          uri: lb:http://HOTEL-MICROSERVICE
          predicates:
            - Path=/hotels/**
          #Payment
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          #User
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/User/**