spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: http://localhost:3306/myBooking
    username: root
    password: 1111
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-hotel"
          jwk-set-uri: "http://localhost:9090/realms/book-hotel/protocol/openid-connect/certs"
    springdoc:
      default-produces-media-type: application/json
keycloak:
  auth-server-url: http://localhost:9090
  realm: book-hotel
  resource: spring-boot-client
  credentials:
    secret: pJrSiE47lYdcQaA2qqrO7T2zg42ERcmJ
  use-resource-role-mappings: true
server:
  port: 1112
