/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HotelResponse } from '../../models/hotel-response';

export interface GetHotelByName$Params {
  hotel: string;
}

export function getHotelByName(http: HttpClient, rootUrl: string, params: GetHotelByName$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelResponse>> {
  const rb = new RequestBuilder(rootUrl, getHotelByName.PATH, 'get');
  if (params) {
    rb.path('hotel', params.hotel, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HotelResponse>;
    })
  );
}

getHotelByName.PATH = '/hotels/{hotel}';
