/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { ForSort } from './models/for-sort';
export type { HotelResponse } from './models/hotel-response';
export type { ListOfBooksResponse } from './models/list-of-books-response';
export type { RoomResponse } from './models/room-response';
