/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
