services:
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin12
      KEYCLOAK_ADMIN_PASSWORD: admin12
    networks:
      - microservices-net
    command:
      - "start-dev"


networks:
  microservices-net:
    driver: bridge

