/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoomResponse {
  hotel_name?: string;
  id?: number;
  location?: string;
  number?: number;
  numberOfBed?: number;
  rate?: 'LUX' | 'FAMILY' | 'ECONOMIC' | 'PRESIDENT';
  worthPerNight?: number;
}
