/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PaymentRequest } from './models/payment-request';
export type { PaymentResponse } from './models/payment-response';
