/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { HotelDb } from './models/hotel-db';
export { HotelRequest } from './models/hotel-request';
export { HotelResponse } from './models/hotel-response';
export { RoomDb } from './models/room-db';
export { RoomResponse } from './models/room-response';
