/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  eviction?: string;
  hotel_name: string;
  paymentType?: 'VISA' | 'MASTER_CARD';
  roomNumber?: number;
  settlement?: string;
  userEmail: string;
}
