/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  eviction?: string;
  hotel_name?: string;
  roomId?: number;
  settlement?: string;
  userEmail?: string;
}
