/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ForSort {
  eviction?: string;
  location?: string;
  maxWorthPerNight?: number;
  minWorthPerNight?: number;
  numberOfBed?: number;
  rate?: 'LUX' | 'FAMILY' | 'ECONOMIC' | 'PRESIDENT';
  settlement?: string;
  stars?: 'ONE' | 'TWO' | 'THREE' | 'FOUR' | 'FIVE';
}
