/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ListOfBooksResponse {
  eviction?: string;
  hotel_name?: string;
  roomNumber?: number;
  settlement?: string;
}
