/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HotelRequest } from '../models/hotel-request';
import { RoomRequest } from '../models/room-request';
export interface FullHotelRequest {
  request: HotelRequest;
  rooms: Array<RoomRequest>;
}
