/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomDb } from './room-db';
export interface HotelRequest {
  location?: string;
  name?: string;
  rooms?: Array<RoomDb>;
  stars?: 'ONE' | 'TWO' | 'THREE' | 'FOUR' | 'FIVE';
}
