/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomResponse } from './room-response';
export interface HotelResponse {
  id?: number;
  location?: string;
  name?: string;
  rooms?: Array<RoomResponse>;
  stars?: 'ONE' | 'TWO' | 'THREE' | 'FOUR' | 'FIVE';
}
