/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HotelRequest {
  location?: string;
  name?: string;
  stars?: 'ONE' | 'TWO' | 'THREE' | 'FOUR' | 'FIVE';
}
