/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoomRequest {
  number?: number;
  numberOfBed?: number;
  rate: 'LUX' | 'FAMILY' | 'ECONOMIC' | 'PRESIDENT';
  worthPerNight?: number;
}
