/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HotelDb } from './hotel-db';
export interface RoomDb {
  hotelDb?: HotelDb;
  id?: number;
  number?: number;
  numberOfBed?: number;
  rate: 'LUX' | 'FAMILY' | 'ECONOMIC' | 'PRESIDENT';
  worthPerNight?: number;
}
