/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { FullHotelRequest } from './models/full-hotel-request';
export type { HotelRequest } from './models/hotel-request';
export type { HotelResponse } from './models/hotel-response';
export type { RoomRequest } from './models/room-request';
export type { RoomResponse } from './models/room-response';
