/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentResponse {
  cardNumber?: number;
  paymentType?: 'VISA' | 'MASTER_CARD';
  userName?: string;
  value?: number;
}
