/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentRequest {
  cardNumber?: number;
  email?: string;
  paymentType?: 'VISA' | 'MASTER_CARD';
  value?: number;
}
