/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ForSort } from '../../models/for-sort';
import { HotelResponse } from '../../models/hotel-response';

export interface SearchFree$Params {
      body: ForSort
}

export function searchFree(http: HttpClient, rootUrl: string, params: SearchFree$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HotelResponse>>> {
  const rb = new RequestBuilder(rootUrl, searchFree.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HotelResponse>>;
    })
  );
}

searchFree.PATH = '/books/search';
